=== wxPerl/WebSite/src/wxperl.dtd
<!-- ********************************************************************** -->
<!-- organisation list                                                      -->
<!-- ********************************************************************** -->

<!ELEMENT organisations (organisation*)>
<!ELEMENT organisation (name, site?, country?, contact?, wxperl,
          applications)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT site (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT contact (name, email)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT applications (application+)>
<!ELEMENT application (name, site, license-type, platforms, wxperl-version,
          domain, short-description, long-description?)>

<!ELEMENT wxperl-version (#PCDATA)>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT short-description (#PCDATA)>
<!ELEMENT long-description (#PCDATA)>

<!ELEMENT wxperl (rating, comments?)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT comments (#PCDATA)>

<!-- application license types -->
<!ELEMENT license-type (commercial | open-source)>
<!ELEMENT commercial EMPTY>
<!ELEMENT open-source EMPTY>

<!-- application platforms -->
<!ELEMENT platforms (windows | linux)>
<!ELEMENT windows EMPTY>
<!ELEMENT linux EMPTY>

<!-- ********************************************************************** -->
<!-- Screenshots                                                            -->
<!-- ********************************************************************** -->

<!ELEMENT screenshots (page)+>
<!ELEMENT page (description, image+)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (text, file)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT file (#PCDATA)>

=== wxPerl/WebSite/src/sshots.xml
<?xml version="1.0"?>
<!DOCTYPE screenshots SYSTEM "wxperl.dtd">

<screenshots xmlns:xhtml="http://www.w3.org/1999/xhtmlAlias">
  <page>
    <description>
This is the "minimal" sample from the wxPerl distribution (you can
find it in <xhtml:tt>samples/minimal/minimal.pl</xhtml:tt>). It shows just
a window with a status bar and a menu bar.
    </description>

    <image>
      <text>Minimal sample (Mac OS X)</text>
      <file>screenshots/minimal_mac.png</file>
    </image>

    <image>
      <text>Minimal sample (Microsoft Windows 2000)</text>
      <file>screenshots/minimal_w2k.png</file>
    </image>

    <image>
      <text>Minimal sample (Solaris, GTK 1.2); courtesy of Valentin Guignon</text>
      <file>screenshots/minimal_gtk_solaris.png</file>
    </image>

    <image>
      <text>Minimal sample (Linux, Motif)</text>
      <file>screenshots/minimal_motif.png</file>
    </image>

    <image>
      <text>Minimal sample (Windows XP); courtesy of Herbert Breunung</text>
      <file>screenshots/minimal_wxp.png</file>
    </image>
  </page>

  <page>
    <description>
This is the "controls" sample from the wxPerl distribution (you can
find it in <xhtml:tt>samples/controls/controls.pl</xhtml:tt>). It shows many of
the controls available in wxPerl.
    </description>

    <image>
      <text>Controls sample (Linux, GTK 1.2); Wx::ComboBox page</text>
      <file>screenshots/controls_gtk.png</file>
    </image>

    <image>
      <text>Controls sample (Microsoft Windows 2000); Wx::ListBox page</text>
      <file>screenshots/controls_w2k.png</file>
    </image>

    <image>
      <text>Controls sample (Linux, Motif); Wx::Choice page</text>
      <file>screenshots/controls_motif.png</file>
    </image>
  </page>

  <page>
    <description>
This is the "dialogs" sample from the wxPerl distribution (you can
find it as <xhtml:tt>samples/dialogs/dialogs.pl</xhtml:tt>). It shows many
of the common dialogs available in wxPerl.
    </description>

    <image>
      <text>Directory selector (Microsoft Windows 2000)</text>
      <file>screenshots/dialogs_dirdialog_w2k.png</file>
    </image>

    <image>
      <text>File selector (Linux, Motif)</text>
      <file>screenshots/dialogs_filedialog_motif.png</file>
    </image>

    <image>
      <text>File selector (Mac OS X)</text>
      <file>screenshots/dialogs_filedialog_mac.png</file>
    </image>

    <image>
      <text>Multiple choice (Microsoft Windows 2000)</text>
      <file>screenshots/dialogs_multichoice_w2k.png</file>
    </image>

    <image>
      <text>Font selector (Linux, GTK 1.2)</text>
      <file>screenshots/dialogs_fontdialog_gtk.png</file>
    </image>

    <image>
      <text>Color selector (Mac OS X)</text>
      <file>screenshots/dialogs_colordialog_mac.png</file>
    </image>
  </page>
</screenshots>
